version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: new_mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "g15" 
      MYSQL_DATABASE: database
      MYSQL_USER: ""
      MYSQL_PASSWORD: ""
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
