version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: new_mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "g15" 
      MYSQL_DATABASE: database
      MYSQL_USER: ""
      MYSQL_PASSWORD: ""
    volumes:
      - mysql_data:/var/lib/mysql

  nodejs:
    build: .
    container_name: nodejs-container
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      - NODE_ENV=production

volumes:
  mysql_data:
